### ISSUE TITLE
CT: Assertion failed: All descendants must be disposed by the next frame

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#250]
This started showing up in CT immediately after I added `"phet-io"` to `"supportedBrands"` in package.json.  It's related to the PhET-iO element `projectorModeCheckbox`, a common-code component that's added to the Options dialog via GeometricOpticsOptionsDialogContent.js.

Note that the PhET-iO implementation for this sim is in early stages, with `"validation": false` in package.json.

```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634806918067%22%2C%22timestamp%22%3A1634825981555%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.projectorModeCheckbox
Error: Assertion failed: All descendants must be disposed by the next frame: geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.projectorModeCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/tandem/js/PhetioObject.js:612:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/tandem/js/PhetioObject.js:611:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/axon/js/TinyEmitter.js:100:41)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634806918067/joist/js/Sim.js:900:25)
id: Bayes Chrome
Snapshot from 10/21/2021, 3:01:58 AM
```

**Comment by pixelzoom** [comment]
To duplicate manually:

1. Run geometric-optics in the State wrapper using phetmarks
2. In the Upstream sim, select PhET menu > Options to open the Options dialog. You'll see the Options dialog open in the Downstream sim.
3. Click the "Projector Mode" checkbox.  The assertion will fail, and you'll see this message in the browser console:
> All descendants must be disposed by the next frame: geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.projectorModeCheckbox
