### ISSUE TITLE
CT: Assertion failed: width must be a finite number: Infinity

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#294]
```
geometric-optics : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1642438312301%22%2C%22timestamp%22%3A1642453727928%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: width must be a finite number: Infinity
Error: Assertion failed: width must be a finite number: Infinity
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/assert/js/assert.js:25:13)
at Shape.rect (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/kite/js/Shape.js:989:15)
at updateClipArea (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/geometric-optics/js/common/view/OpticalAxisForegroundNode.js:75:73)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/geometric-optics/js/common/view/OpticalAxisForegroundNode.js:90:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/axon/js/Emitter.js:37:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/axon/js/Action.js:195:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/axon/js/Emitter.js:62:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/geometric-optics/js/common/model/LightRays.js:73:33
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1642438312301/chipper/dist/js/axon/js/Multilink.js:46:11)
id: Bayes Chrome
Snapshot from 1/17/2022, 9:51:52 AM
```

**Comment by pixelzoom** [comment]
Since we don't have source maps working for TypeScript, I had to manually inspect .js and map to .ts.  The assertion occurs in the call the `new Shape` on line 106 of OpticalAxisForegroundNode.js:

```js
          clipArea = new Shape()
            .rect( x1, minY, clipWidth1, clipHeight )
            .rect( x2, minY, clipWidth2, clipHeight );
```

**Comment by pixelzoom** [comment]
Fixed, CT is happy, closing.
