### ISSUE TITLE
Ray tracer fails when the light position is on (or close to) the optical axis

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#302]
There are problems in the ray tracer when the light source position is on (or close to) the optical axis. Discovered when I was adjusting the initial position of the light sources for #217. 

If the initial position of a light source is (0,0), this assertion failure occurs:

```
Vector2.js? [sm]:257 Uncaught Error: Cannot normalize a zero-magnitude vector
    at Vector2.normalized (Vector2.js? [sm]:257:13)
    at getRayDirections (LightRays.ts:133:40)
    at LightRays.ts:85:28
    at new Multilink (Multilink.ts:77:7)
    at Function.multilink (Property.ts:514:12)
    at new LightRays (LightRays.ts:71:14)
...
```

If the initial position of a light source is (0,1), this assertion failure occurs:

```
Uncaught Error: Assertion failed: the direction must be a unit vector
    at window.assertions.assertFunction (assert.js:25:13)
    at new Ray2 (Ray2.js? [sm]:23:15)
    at new GORay (GORay.ts:26:5)
    at getTransmittedRay (LightRay.ts:335:10)
    at getRealRays (LightRay.ts:233:30)
    at new LightRay (LightRay.ts:77:21)
    at LightRays.ts:94:28
    at Array.forEach (<anonymous>)
    at LightRays.ts:91:20
...
```

**Comment by pixelzoom** [comment]
This is likely a problem with any optical object, not just the lights.

**Comment by pixelzoom** [comment]
The problem in both of these cases is that the x position is too close to the optic.   Values like (100,0) work fine, which is what I was concerned with when I tried (0,0) --- values where the object is on the optical axis.

I'll investigate adding validation to OpticalObject positionProperty, so that values that are too close to the optic will fail in PhET-iO.
