### ISSUE TITLE
CT: the direction must be a unit vector

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#305]
First appearance of this CT issue, 2/11/2022, 7:14:53 PM:

```
geometric-optics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644632093889%22%2C%22timestamp%22%3A1644634585798%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: the direction must be a unit vector
Error: Assertion failed: the direction must be a unit vector
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/assert/js/assert.js:25:13)
at new Ray2 (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/dot/js/Ray2.js:22:15)
at new GORay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/geometric-optics/js/common/model/GORay.js:21:5)
at getTransmittedRay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/geometric-optics/js/common/model/LightRay.js:269:10)
at getRealRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/geometric-optics/js/common/model/LightRay.js:181:30)
at new LightRay (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/geometric-optics/js/common/model/LightRay.js:48:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/geometric-optics/js/common/model/LightRays.js:63:26
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/geometric-optics/js/common/model/LightRays.js:61:18
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644632093889/chipper/dist/js/axon/js/Multilink.js:46:11)
id: Bayes Chrome
Snapshot from 2/11/2022, 7:14:53 PM
```

**Comment by pixelzoom** [comment]
This is no longer occurring in CT.  And I cannot reproduce locally with `?brand=phet&ea&fuzz`.  So this was probably an intermediate problem while I was refactoring or working on the Arrow feature.  

Closing.
