### ISSUE TITLE
CT: x should be a finite number

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#306]
First appearance of this CT issue, 2/11/2022, 2:11:07 PM:
```
geometric-optics : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644613867600%22%2C%22timestamp%22%3A1644617545064%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: x should be a finite number
Error: Assertion failed: x should be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/assert/js/assert.js:25:13)
at CueingArrowsNode.translate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/scenery/js/nodes/Node.js:2068:17)
at CueingArrowsNode.setRight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/scenery/js/nodes/Node.js:2734:12)
at CueingArrowsNode.set right [as right] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/scenery/js/nodes/Node.js:2745:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/geometric-optics/js/common/view/ArrowObjectNode.js:80:30
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyStaticProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at TinyStaticProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/axon/js/TinyStaticProperty.js:53:10)
at ArrowNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/scenery/js/nodes/Node.js:1202:31)
at TinyStaticProperty.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644613867600/chipper/dist/js/axon/js/TinyStaticProperty.js:27:10)
id: Bayes Chrome
Snapshot from 2/11/2022, 2:11:07 PM
```

**Comment by pixelzoom** [comment]
To reproduce locally,  use this option value in LensModel.ts. y=0 is what's important here, resulting in a zero-magnitude arrow.

```ts
arrowObject1Position: new Vector2( -160, 0 ),
```

The TypeScript stack trace is:

```
Uncaught Error: Assertion failed: x should be a finite number
    at window.assertions.assertFunction (assert.js:25:13)
    at CueingArrowsNode.translate (Node.ts:2240:17)
    at CueingArrowsNode.setRight (Node.ts:2850:12)
    at CueingArrowsNode.set right [as right] (Node.ts:2859:10)
    at ArrowObjectNode.ts:156:9
    at new Multilink (Multilink.ts:77:7)
    at Function.multilink (Property.ts:514:12)
    at new ArrowObjectNode (ArrowObjectNode.ts:154:14)
    at new ArrowObjectSceneNode (ArrowObjectSceneNode.ts:79:30)
    at new GOScreenView (GOScreenView.ts:272:34)
```
