### ISSUE TITLE
CT: Assertion failed: Should be empty before adding everything

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#316]
This occurred once (so far) in the State Wrapper.  It's in `GORulerNode.onVisiblePropertyChange`, so probably related to a ruler transitioning in/out of the toolbox.

```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644979446092%22%2C%22timestamp%22%3A1644984737723%7D
Uncaught Error: Uncaught Error: Assertion failed: Should be empty before adding everything
Error: Assertion failed: Should be empty before adding everything
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/assert/js/assert.js:25:13)
at PDOMDisplaysInfo.addAllPDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:173:15)
at PDOMDisplaysInfo.onVisibilityChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:100:14)
at GORulerNode.onVisiblePropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/scenery/js/nodes/Node.js:3380:28)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/axon/js/TinyEmitter.js:53:48)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/axon/js/TinyForwardingProperty.js:139:10)
at TinyForwardingProperty.onTargetPropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/axon/js/TinyForwardingProperty.js:97:10)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/axon/js/Property.js:228:23)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644979446092/chipper/dist/js/axon/js/Property.js:276:47)
id: Bayes Chrome
Snapshot from 2/15/2022, 7:44:06 PM
```

**Comment by pixelzoom** [comment]
@zepumph I'm wondering if you've seen this error before, and if it's perhaps related to https://github.com/phetsims/geometric-optics/issues/318 and/or https://github.com/phetsims/scenery/issues/1312.

**Comment by zepumph** [comment]
It seems like a pretty good bet that this is the same sort of thing as what you mentioned. I'll stay assigned for now.

**Comment by pixelzoom** [comment]
I'll defer this issue, pending fix for https://github.com/phetsims/scenery/issues/1312.

**Comment by zepumph** [comment]
A fix has been pushed over in https://github.com/phetsims/scenery/issues/1312#issuecomment-1047142324, next steps for this issue are to make sure it is being tested on CT in the state wrapper. This will ensure we got the fix correct.

**Comment by pixelzoom** [comment]
The `phet-io-state-fuzz` test is not being run very often by CT.  It's only run 3 times since the fix for https://github.com/phetsims/scenery/issues/1312 was pushed, see screenshot below.  @zepumph do you feel comfortable closing with this kind of CT coverage?

<img width="1299" alt="screenshot_1570" src="https://user-images.githubusercontent.com/3046552/155185725-466690ee-5ba5-41a6-a220-9165c6e65ee5.png">

**Comment by zepumph** [comment]
Yes, I feel alright when I take those tests and add them to my local testing. Before the change, either https://github.com/phetsims/geometric-optics/issues/318 or https://github.com/phetsims/geometric-optics/issues/316 would be hit within ~ 5 seconds of state fuzz testing. Closing

Please also note https://github.com/phetsims/geometric-optics/issues/325 is a state wrapper fuzz bug too at this time.
