### ISSUE TITLE
CT: Assertion failed: there should be at least as many PDOMDisplays as Displays

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#318]
This CT failure is occurring in the State Wrapper, related to PDOM.  @zepumph @jessegreenberg any advice on how approach debugging this?

```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645086359601%22%2C%22timestamp%22%3A1645094346332%7D
Uncaught Error: Uncaught Error: Assertion failed: there should be at least as many PDOMDisplays as Displays
Error: Assertion failed: there should be at least as many PDOMDisplays as Displays
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/assert/js/assert.js:25:13)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:243:15)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:261:35)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:261:35)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:261:35)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:261:35)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:261:35)
at PDOMDisplaysInfo.removeAllPDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:204:10)
at PDOMDisplaysInfo.onVisibilityChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:102:14)
at LensScreenView.onVisiblePropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645086359601/chipper/dist/js/scenery/js/nodes/Node.js:3380:28)
id: Bayes Chrome
Snapshot from 2/17/2022, 1:25:59 AM
```

**Comment by zepumph** [comment]
This is a big one. 

Other sims:
https://github.com/phetsims/circuit-construction-kit-common/issues/760
https://github.com/phetsims/greenhouse-effect/issues/46 (lots of investigation/back story in this one)

Underlying problem:
https://github.com/phetsims/scenery/issues/1312

It may be good to check in on the priority of that issue, and to make higher ups aware of it again.

**Comment by zepumph** [comment]
A fix has been pushed over in https://github.com/phetsims/scenery/issues/1312#issuecomment-1047142324, next steps for this issue are to make sure it is being tested on CT in the state wrapper. This will ensure we got the fix correct.

**Comment by pixelzoom** [comment]
The `phet-io-state-fuzz` is not being run very often by CT.  It's only run 3 times since the fix for https://github.com/phetsims/scenery/issues/1312 was pushed, see screenshot below.  @zepumph do you feel comfortable closing with this kind of CT coverage?

<img width="1299" alt="screenshot_1570" src="https://user-images.githubusercontent.com/3046552/155185725-466690ee-5ba5-41a6-a220-9165c6e65ee5.png">

**Comment by zepumph** [comment]
Yes, I feel alright when I take those tests and add them to my local testing. Before the change, either https://github.com/phetsims/geometric-optics/issues/318 or https://github.com/phetsims/geometric-optics/issues/316 would be hit within ~ 5 seconds of state fuzz testing. Closing
