### ISSUE TITLE
CT: Assertion failed: scale should be finite

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#321]
The first time that this occurred in CT was Saturday 2/19/2022 @ 3:31:37 AM.  I hadn't touched the code since Thu 2/18/2022 @ 8:57PM.   So I'm wondering if this is a common-code regression.

```
geometric-optics : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645266697421%22%2C%22timestamp%22%3A1645300547953%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: scales should be finite
Error: Assertion failed: scales should be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/assert/js/assert.js:25:13)
at Node.scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/scenery/js/nodes/Node.js:2120:17)
at updateScaleAndPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/geometric-optics/js/common/view/FramedImageNode.js:64:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/geometric-optics/js/common/view/FramedImageNode.js:69:43
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645266697421/chipper/dist/js/axon/js/Property.js:228:23)
id: Bayes Chrome
Snapshot from 2/19/2022, 3:31:37 AM
```

**Comment by pixelzoom** [comment]
Manually mapping the .js assertion to FramedImageNode.ts, it's line 88:

```ts
      const scaleX = ( viewBounds.width / initialWidth ) || GOConstants.MIN_SCALE; // prevent zero scale
      const scaleY = ( viewBounds.height / initialHeight ) || GOConstants.MIN_SCALE; // prevent zero scale
88    parentNode.scale( scaleX, scaleY );
```

**Comment by pixelzoom** [comment]
This has not occurred in the 4 most-recent CT cycles. It has not occurred since 2/20/2022 @ 1:30:34 AM.  And CT seems to have restarted, so I can't tell how many times it occurred since the first occurrence on 2/19/2022 @ 3:31:37.   So before spending more time on this, I'm going to wait to see if it reoccurs, or was perhaps some transient common-code issue.

**Comment by pixelzoom** [comment]
Still nothing in CT, so closing.

**Comment by pixelzoom** [comment]
Reopening. This occurred once:

```
geometric-optics : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1646128908517%22%2C%22timestamp%22%3A1646131689502%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: scales should be finite
Error: Assertion failed: scales should be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/assert/js/assert.js:25:13)
at Node.scale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/scenery/js/nodes/Node.js:2120:17)
at updateScaleAndPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/geometric-optics/js/common/view/FramedImageNode.js:62:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/geometric-optics/js/common/view/FramedImageNode.js:67:43
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646128908517/chipper/dist/js/axon/js/Property.js:228:23)
id: Bayes Chrome
Snapshot from 3/1/2022, 3:01:48 AM
```

**Comment by pixelzoom** [comment]
I suspect that parentNode has zero bounds because the Image node that it wraps does not have valid bounds -- for some reason. In the above commit, I've added assertions with messages that will help me (dis)prove this theory.

**Comment by pixelzoom** [comment]
I haven't seen this failure since 3/1/2022.

**Comment by pixelzoom** [comment]
I fuzzed tested the unbuilt sim for 30 minutes and did not encounter this problem.
URL: `geometric-optics_en.html?brand=phet&ea&debugger&fuzz`

**Comment by pixelzoom** [comment]
This is a non-blocking error. It won't cause the sim to crash, and is unlikely to result in any noticeable problems in practice.   1.1 was published with this as a known issue.

**Comment by KatieWoe** [comment]
Can you confirm if this issue is still needed? I don't see it in CT right now, but it is noted as rare. For https://github.com/phetsims/qa/issues/832

**Comment by pixelzoom** [comment]
Yes, please keep this open.

**Comment by pixelzoom** [comment]
It is not necessary to address this for #278, the 1.3 PhET-iO release.

**Comment by pixelzoom** [comment]
Still occurring occassionally, last seen 5/4/23 @ 10:56AM.

**Comment by pixelzoom** [comment]
Still occurring occassionally, last seen 9/25/2023, 11:16:26 PM.  I still cannot reproduce locally.

```
geometric-optics : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1695705386589/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695705386589%22%2C%22timestamp%22%3A1695706354264%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: scale should be finite: scaleX=Infinity, initialWidth=0 viewBounds.width=241012948808499200scaleY=2111062325329920.8, initialHeight=0 viewBounds.height=241012948808499200
Error: Assertion failed: scale should be finite: scaleX=Infinity, initialWidth=0 viewBounds.width=241012948808499200scaleY=2111062325329920.8, initialHeight=0 viewBounds.height=241012948808499200
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695705386589/assert/js/assert.js:28:13)
at assert (FramedImageNode.ts:66:16)
at updateScaleAndPosition (FramedImageNode.ts:75:43)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (DerivedProperty.ts:157:12)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695705386589%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695705386589%22%2C%22timestamp%22%3A1695706354264%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695705386589%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1695705386589%22%2C%22timestamp%22%3A1695706354264%7D
...
id: "Sparky Node Puppeteer"
Snapshot from 9/25/2023, 11:16:26 PM
```

**Comment by pixelzoom** [comment]
After addressing #487, this is occurring again in CT:

```
geometric-optics : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1703715702864%22%2C%22timestamp%22%3A1703716268833%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: scale should be finite: scaleX=Infinity, initialWidth=0 viewBounds.width=241012948808499200 scaleY=2849934139195391.5, initialHeight=0 viewBounds.height=241012948808499200
Error: Assertion failed: scale should be finite: scaleX=Infinity, initialWidth=0 viewBounds.width=241012948808499200 scaleY=2849934139195391.5, initialHeight=0 viewBounds.height=241012948808499200
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/assert/js/assert.js:28:13)
at assert (FramedImageNode.ts:66:16)
at updateScaleAndPosition (FramedImageNode.ts:75:43)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (DerivedProperty.ts:174:12)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1703715702864%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1703715702864%22%2C%22timestamp%22%3A1703716268833%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1703715702864%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1703715702864%22%2C%22timestamp%22%3A1703716268833%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1703715702864%22%2C%22timestamp%22%3A1703716268833%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 829371
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: scale should be finite: scaleX=Infinity, initialWidth=0 viewBounds.width=241012948808499200 scaleY=2849934139195391.5, initialHeight=0 viewBounds.height=241012948808499200
[PAGE ERROR] Error: Error: Assertion failed: scale should be finite: scaleX=Infinity, initialWidth=0 viewBounds.width=241012948808499200 scaleY=2849934139195391.5, initialHeight=0 viewBounds.height=241012948808499200
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/assert/js/assert.js:28:13)
at updateScaleAndPosition (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/geometric-optics/js/common/view/FramedImageNode.js:45:17)
at http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/geometric-optics/js/common/view/FramedImageNode.js:49:43
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/DerivedProperty.js:119:13)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1703715702864/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 12/27/2023, 3:21:42 PM
```

**Comment by pixelzoom** [comment]
Addressed in the above commit by testing for both zero and non-finite scale.  I'll leave this open for a few cycles to verify that CT is happy.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
