### ISSUE TITLE
Assertion failed: reentry detected, value=Vector2(-246, 75), oldValue=Vector2(-272.8488146551724, 75)

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#325]
While manually testing the state wrapper for https://github.com/phetsims/geometric-optics/issues/318, I am able to hit this assertion in ~60 seconds most runs. I have hit it 3+ times now, so I thought I'd make an issue since it seems a bit too rare for CT to be picking it up at this time.

```

assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=Vector2(-246, 75), oldValue=Vector2(-272.8488146551724, 75)
    at window.assertions.assertFunction (assert.js:25:13)
    at Vector2Property._notifyListeners (Property.ts:286:15)
    at Vector2Property.set (Property.ts:223:14)
    at Vector2Property.set value [as value] (Property.ts:359:10)
    at FramedObjectNode.ts:140:7
    at TinyProperty.emit (TinyEmitter.ts:93:9)
    at DerivedProperty._notifyListeners (Property.ts:289:23)
    at DerivedProperty.set (Property.ts:223:14)
    at DerivedProperty.getDerivedPropertyListener (DerivedProperty.ts:131:13)
    at TinyProperty.emit (TinyEmitter.ts:93:9)

```

**Comment by pixelzoom** [comment]
> While manually testing the state wrapper ....

It sounds like I'll probably reproduce this by randomly poking around in the sim while it's running in the State Wrapper. But could you give me some steps to reproduce, so that I'm sure that we're doing the same thing?

**Comment by zepumph** [comment]
I was just running the state wrapper with ?fuzz and the console open.

**Comment by pixelzoom** [comment]
I'm guessing that this is being caused by changing the zoom level while dragging. That results in the drag bounds changing and the object having to be repositioned, causing reentry of `positionProperty` and `dragBoundsProperty`.  It's probably not specific to `FramedObjectNode`.   And (if my hypothesis is correct) I'm wondering why it would be specific to the State Wrapper.  

A solution might be to change this:

```ts
// FramedObjectNode.ts

    dragBoundsProperty.link( dragBounds => {
      framedObject.positionProperty.value = dragBounds.closestPointTo( framedObject.positionProperty.value );
    } );
```

... to change first call `interruptSubtreeInput`, then change `framedObject.positionProperty` in the next animation frame.

**Comment by pixelzoom** [comment]
> I was just running the state wrapper with ?fuzz and the console open.

That's impossible -- the State Wrapper doesn't work with `?fuzz`.  I'm guessing you used `?sim=geometric-optics&phetioDebug&fuzz`.

Reproduced in my working copy after running for ~3 minutes with `?sim=geometric-optics&phetioDebug&fuzz`.

**Comment by pixelzoom** [comment]
Before making any changes, I ran `geometric-optics_en.html?brand=phet&ea&debugger&initialScreen=1&fuzz` and could not reproduce the problem.  So it is apparently specific to the State Wrapper

I added `interruptSubtreeInput` as proposed in https://github.com/phetsims/geometric-optics/issues/325#issuecomment-1049447491, and that seems to have been sufficient to fix the problem. I tested with `?sim=geometric-optics&phetioDebug&fuzz` for ~20 minutes and the error no longer occurs.

@zepumph could you please verify? Any thoughts on why this resolved the error? I don't understand this at all.

**Comment by pixelzoom** [comment]
Oh boy.... Back to me.  The reason that the error no longer occurs is because those `interruptSubtreeInput` calls are preventing objects from being dragged.

**Comment by pixelzoom** [comment]
As reported by @KatieWoe in https://github.com/phetsims/geometric-optics/issues/341... After factoring out base class HTMLImageElementObjectNode, this error moved from FramedObjectNode to HTMLImageElementObjectNode: 

```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645997920856%22%2C%22timestamp%22%3A1646035369031%7D
Uncaught Error: Uncaught Error: Assertion failed: reentry detected, value=Vector2(-708, -21), oldValue=Vector2(-818.260452586207, -21)
Error: Assertion failed: reentry detected, value=Vector2(-708, -21), oldValue=Vector2(-818.260452586207, -21)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/assert/js/assert.js:25:13)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:226:15)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:159:14)
at Vector2Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:298:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/geometric-optics/js/common/view/HTMLImageElementObjectNode.js:100:48
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 2/27/2022, 2:38:40 PM
```

**Comment by pixelzoom** [comment]
Addressed in the above commits by adjusting object's `positionProperty` in the next animation frame, and removing all usages of `reentrant: true`.   Ran with `?fuzz` in standalone and State Wrapper for 15 minutes each, didn't see any problems.

Closing.
