### ISSUE TITLE
CT:  Cannot read properties of null (reading 'pointer')

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#363]
First occurrence was 3/9/2022 @ 7:22 PM.  Probably related to work in #355.
```
geometric-optics : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'pointer')
TypeError: Cannot read properties of null (reading 'pointer')
at rq.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:1570105)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:680703
at rq.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:673708)
at Od.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:549197)
at rq.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:671701)
at rq.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:680642)
at rq.interrupt (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:672155)
at rq.interrupt (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:683835)
at rq.pointerCancel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:674093)
at Zu.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646907990922/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1646907990922%22%2C%22timestamp%22%3A1646911584315%7D&fuzz&memoryLimit=1000:882:649495)
id: Bayes Chrome
Snapshot from 3/10/2022, 3:26:30 AM
```

**Comment by pixelzoom** [comment]
This is failing because the `end` function for GOToolDragListener is receiving a null event,

Slack to @jonathanolson:

GOToolDragListener is a DragListener subclass, and I’m passing it an end function via options:

```
      end: ( event: PressListenerEvent | null ) => {
        assert && assert( event ); // {PressListenerEvent|null}
        if ( shouldReturnToToolbox( event!.pointer.point ) ) {
          tool.isInToolboxProperty.value = true;
        }
      }
```

I’m not doing anything to synthetically call `end` , so I expected (based on reading the doc) that event should be non-null.  But with fuzz testing, it’s receiving a null event, and failing with stack trace:

> assert.js:25 Uncaught Error: Assertion failed
    at window.assertions.assertFunction (assert.js:25:13)
    at GOToolDragListener.end [as _end] (GOToolDragListener.ts:49:19)
    at DragListener.ts:392:25
    at GOToolDragListener.onRelease (PressListener.ts:720:17)
    at PhetioAction.execute (PhetioAction.ts:120:17)
    at GOToolDragListener.release (PressListener.ts:507:25)
    at GOToolDragListener.release (DragListener.ts:388:11)
    at GOToolDragListener.interrupt (PressListener.ts:577:12)
    at GOToolDragListener.interrupt (DragListener.ts:798:11)
    at GOToolDragListener.pointerCancel (PressListener.ts:840:12)

Can you help me understand what (or whether) I’m doing something wrong?

**Comment by pixelzoom** [comment]
Slack:

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [3:21 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646950863602069)
Interrupt doesn't take an event, so it can't be passed through
PointerCancel is presumably from a gesture that cancels the interaction?

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [3:54 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646952888903229)
I see.  The idea is that when the drag ends, a tool is returned to the toolbox if the pointer was inside the toolbox bounds.  But I guess I can’t check where the pointer was when interrupted (or can I?) So perhaps I should just ignore null on end and do nothing? That could leave a tool on top of the toolbox, when it technically should be in the toolbox. (edited) 

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [4:32 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646955157108749)
Wouldn't you want to check whether the tool is over the toolbox instead of where the pointer was?

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [4:54 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646956486068779)
No. The rulers are huge. They are allowed to overlap the toolbox.
In fact, for keyboard drag, the rulers are only returned to the toolbox when their center point is in the toolbox bounds.
For mouse/touch drag, the explicit requirement is when the pointer is inside the toolbox. 

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [5:28 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646958528544669)
Then how would an interrupt with no event work? Presumably best to keep track of the last interaction point.
So “if it’s interrupted and the last pointer position was over the toolbox, put it back”

**Comment by pixelzoom** [comment]
GOToolDragListener is now keeping track of event.pointer.point in `drag`. If `end` is called with no event, it uses the last event that it got from `drag`.   This seems to work with fuzz testing. I'll leave this issue open to confirm that CT is happy.

**Comment by pixelzoom** [comment]
CT is happy. Closing.
