### ISSUE TITLE
CT: Cannot handle messages until after initialization

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#386]
```
geometric-optics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics&phetioDebug
1 out of 2 tests passed. 1 failed.
SimTests: geometric-optics: iframe API failed:
Uncaught Error: Cannot handle messages until after initialization
Error: Cannot handle messages until after initialization
at PhetioCommandProcessor.sendAPIRequestError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:203:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:66:16

Uncaught Error: Cannot handle messages until after initializationError: Cannot handle messages until after initialization
at PhetioCommandProcessor.sendAPIRequestError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:203:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:66:16
id: Bayes Chrome
Snapshot from 3/17/2022, 8:34:38 PM
```

**Comment by pixelzoom** [comment]
I don't know where to start with this one. @zepumph @samreid thoughts?

**Comment by samreid** [comment]
My local copy shows no errors for http://localhost/main/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics, and http://localhost/main/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics&phetioDebug fails with "too many query parameters" error.  @zepumph can you please advise?

**Comment by pixelzoom** [comment]
`/phet-io-wrappers/phet-io-wrappers-tests.html?sim=geometric-optics&phetioDebug` fails for me with "Assertion failed: query parameter cannot occur multiple times" , stack trace below.  @samreid is that what you mean by  "too many query parameters" error, or are you seeing something else? And is this related or a different problem? 

```
QueryStringMachine.js:680 Uncaught Error: Query String Machine Assertion failed: query parameter cannot occur multiple times
    at queryStringMachineAssert (QueryStringMachine.js:680:15)
    at parseValues (QueryStringMachine.js:558:7)
    at Object.getForString (QueryStringMachine.js:154:21)
    at Object.getAllForString (QueryStringMachine.js:214:34)
    at Object.getAll (QueryStringMachine.js:130:21)
    at initialize-globals.js:709:62
    at initialize-globals.js:810:4
    at initialize-globals.js:936:2
queryStringMachineAssert @ QueryStringMachine.js:680
parseValues @ QueryStringMachine.js:558
getForString @ QueryStringMachine.js:154
getAllForString @ QueryStringMachine.js:214
getAll @ QueryStringMachine.js:130
(anonymous) @ initialize-globals.js:709
(anonymous) @ initialize-globals.js:810
(anonymous) @ initialize-globals.js:936
getStringModule.js? [sm]:33 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at getStringModule (getStringModule.js? [sm]:33:28)
    at geometricOpticsStrings.ts:81:32
```

**Comment by zepumph** [comment]
There is a general problem that I am aware of with phet-io-wrappers-tests, they need some work. I only just realized the vast majority of them weren't reporting their errors during a call with JO earlier this week.  I feel like this issue will get sorted out over in that issue.

**Comment by pixelzoom** [comment]
Thanks @zepumph. I'll unassign us for now, and put this issue "on-hold" until https://github.com/phetsims/phet-io-wrappers/issues/434 is addressed.

**Comment by pixelzoom** [comment]
Since this is a general problem with phet-io-wrappers-tests, will presumably be fixed/tested generally, and is afaik not blocking...  I'm going to go ahead and close this sim-specific issue, because there's nothing sim-specific to be done.
