### ISSUE TITLE
CT phetioID already registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#391]
```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647730041343%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.add2FPointsCheckbox
Error: Assertion failed: phetioID already registered: geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.add2FPointsCheckbox
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/phet-io/js/phetioEngine.js:631:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/phet-io/js/phetioEngine.js:1122:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/tandem/js/Tandem.js:156:36)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/tandem/js/PhetioObject.js:242:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:6065:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Text.js:198:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:6044:10)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Text.js:80:18)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Text.js:69:10)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM
```

**Comment by pixelzoom** [comment]
Hmmm... I thought this had been was fixed in https://github.com/phetsims/phet-io/issues/1853 on 3/17/2022 @ 10:41AM.  I'll investigate.

**Comment by pixelzoom** [comment]
Reproduced manaully by:

1. Run the sim in  State wrapper with `phet-io-wrappers/state/?sim=geometric-optics&phetioDebug`.
2. In the upstream sim, open the Options dialog.
3. Wait ~3 seconds and the assertion should fail.

In the above commits, I fixed this error and improved the iO instrumentation.  Tested with the above steps in my working copy.  I'll leave this open to make sure that CT is happy.
