### ISSUE TITLE
CT: assertion failure in kite.Graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#419]
No assertion message for this one, so I'll have to investigate.

```
geometric-optics : fuzz : unbuilt : fuzzLight
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22fuzzLight%22%5D%2C%22snapshotName%22%3A%22snapshot-1648925503062%22%2C%22timestamp%22%3A1648951254249%7D&brand=phet&ea&fuzz&memoryLimit=1000&screens=1&scene=light
Query: brand=phet&ea&fuzz&memoryLimit=1000&screens=1&scene=light
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/assert/js/assert.js:25:13)
at Graph.computeWindingMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/kite/js/ops/Graph.js:1425:19)
at Graph.computeSimplifiedFaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/kite/js/ops/Graph.js:306:10)
at Function.binaryResult (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/kite/js/ops/Graph.js:1627:11)
at getLightSpotShape (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/geometric-optics/js/common/model/LightSpot.js:106:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/geometric-optics/js/common/model/LightSpot.js:43:293
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/axon/js/DerivedProperty.js:26:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/axon/js/DerivedProperty.js:112:17)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648925503062/chipper/dist/js/axon/js/Property.js:218:23)
id: Bayes Chrome
Snapshot from 4/2/2022, 12:51:43 PM
```

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/geometric-optics/issues/72
