### ISSUE TITLE
CT: phetioID already registered: ... `directRadioButton.labelText`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#427]
Showed up in CT once for geometric-optics-basics, but would also occur for geometric-optics.

```
geometric-optics-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/phet-io-wrappers/state/?sim=geometric-optics-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649905171348%22%2C%22timestamp%22%3A1649909837357%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: geometricOpticsBasics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.focalLengthModelControl.radioButtonGroup.directRadioButton.labelText
Error: Assertion failed: phetioID already registered: geometricOpticsBasics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.content.focalLengthModelControl.radioButtonGroup.directRadioButton.labelText
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/phet-io/js/phetioEngine.js:622:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/phet-io/js/phetioEngine.js:1113:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/tandem/js/Tandem.js:157:36)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/tandem/js/PhetioObject.js:242:17)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/scenery/js/nodes/Node.js:6071:11)
at Text.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/scenery/js/nodes/Text.js:197:11)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/scenery/js/nodes/Node.js:6050:10)
at Text.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/scenery/js/nodes/Text.js:80:18)
at new Text (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649905171348/chipper/dist/js/scenery/js/nodes/Text.js:69:10)
id: Bayes Chrome
Snapshot from 4/13/2022, 8:59:31 PM
```

**Comment by pixelzoom** [comment]
To reproduce locally, run the sim in the State wrapper: 
`phet-io-wrappers/state/?sim=geometric-optics&phetioDebug`.  In the upstream sim, select PhET > Options, and the exception will occur.

**Comment by pixelzoom** [comment]
Fixed in the above commit.

This is another one of those bugs that CT is not good a locating, because the chances that it will open the Options dialog are small.  See https://github.com/phetsims/aqua/issues/136
