### ISSUE TITLE
CT: Assertion failed: reentry detected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#487]
After addressing missing dependencies in https://github.com/phetsims/geometric-optics/issues/486, CT is now reporting:

```
geometric-optics-basics : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1700341783704%22%2C%22timestamp%22%3A1700342328289%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: reentry detected, value=[x:(-251.5,-40),y:(60,60)], oldValue=[x:(-251.5,-40),y:(60,60)]
Error: Assertion failed: reentry detected, value=[x:(-251.5,-40),y:(60,60)], oldValue=[x:(-251.5,-40),y:(60,60)]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:325:14)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (DerivedProperty.ts:174:12)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (Property.ts:54:10)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1700341783704%2Fgeometric-optics-basics%2Fgeometric-optics-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1700341783704%22%2C%22timestamp%22%3A1700342328289%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1700341783704%2Fgeometric-optics-basics%2Fgeometric-optics-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1700341783704%22%2C%22timestamp%22%3A1700342328289%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1700341783704%22%2C%22timestamp%22%3A1700342328289%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: reentry detected, value=[x:(-251.5,-40),y:(60,60)], oldValue=[x:(-251.5,-40),y:(60,60)]
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=[x:(-251.5,-40),y:(60,60)], oldValue=[x:(-251.5,-40),y:(60,60)]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/assert/js/assert.js:28:13)
at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:15)
at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/DerivedProperty.js:119:13)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/Property.js:48:11)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(-251.5, 60), oldValue=Vector2(-251.5, 60)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(-251.5, 60), oldValue=Vector2(-251.5, 60)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/assert/js/assert.js:28:13)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/Property.js:48:11)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:216:12
at DragListener.onPress (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/PressListener.js:528:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.press (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/PressListener.js:302:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(-251.5, 60), oldValue=Vector2(-251.5, 60)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(-251.5, 60), oldValue=Vector2(-251.5, 60)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/assert/js/assert.js:28:13)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/Property.js:48:11)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:216:12
at DragListener.onPress (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/PressListener.js:528:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.press (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/PressListener.js:302:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(-40, 60), oldValue=Vector2(-251.5, 60)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(-40, 60), oldValue=Vector2(-251.5, 60)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/assert/js/assert.js:28:13)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/axon/js/Property.js:48:11)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
at DragListener.pointerMove (http://128.138.93.172/continuous-testing/ct-snapshots/1700341783704/chipper/dist/js/scenery/js/listeners/PressListener.js:681:14)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 11/18/2023, 2:09:43 PM
```

**Comment by pixelzoom** [comment]
Here's a more useful stack trace:

```
window.assertions.assertFunction (assert.js:26)
_notifyListeners (ReadOnlyProperty.ts:325)
unguardedSet (ReadOnlyProperty.ts:276)
set (ReadOnlyProperty.ts:260)
getDerivedPropertyListener (DerivedProperty.ts:174)
emit (TinyEmitter.ts:123)
_notifyListeners (ReadOnlyProperty.ts:329)
unguardedSet (ReadOnlyProperty.ts:276)
set (ReadOnlyProperty.ts:260)
value (Property.ts:54)
(anonymous) (ArrowObjectNode.ts:101)
...
```

Here's the relevant code, showing line 101.  The problem is that dragBoundsProperty depends on arrowObject.positionProperty,  and the dragBoundsProperty listener modifies arrowObject.positionProperty -- hence the reentry.

```ts
  const dragBoundsProperty = new DerivedProperty(
      [ sceneBoundsProperty, objectDragModeProperty, optic.positionProperty, arrowObject.positionProperty ],
...
    // Keep the arrow inside the drag bounds.
    dragBoundsProperty.link( dragBounds => {

      // Do not disturb positionProperty when restoring PhET-iO state.
      if ( !isSettingPhetioStateProperty.value ) {
101     arrowObject.positionProperty.value = dragBounds.closestPointTo( arrowObject.positionProperty.value );
      }
    } );
```

**Comment by pixelzoom** [comment]
Fixed in the above commit by making positionProperty `reentrant: true`.  I'll leave this open for a few CT cycles to verify.

**Comment by pixelzoom** [comment]
There is still a reenty problem occurring in CT, details below.  The fix I made in https://github.com/phetsims/geometric-optics/commit/9bf4d44d232a00291ecc7b6d8eff0618cb5dcdc7 was for OpticalObject and its subclasses. It looks like the current CT error is also related to a Vector2, so I suspect that it's related to some other class that has a `positionProperty` and `dragBoundsProperty`.

```
geometric-optics : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737017156%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: reentry detected, value=[x:(-251.5,-40),y:(-80,80)], oldValue=[x:(-251.5,-40),y:(-80,80)]
Error: Assertion failed: reentry detected, value=[x:(-251.5,-40),y:(-80,80)], oldValue=[x:(-251.5,-40),y:(-80,80)]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:325:14)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (DerivedProperty.ts:174:12)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (Property.ts:54:10)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737017156%7D
...
id: "Sparky Node Puppeteer"
Snapshot from 12/16/2023, 4:19:31 AM
```

**Comment by pixelzoom** [comment]
Above, I said:
> ... I suspect that it's related to some other class that has a `positionProperty` and `dragBoundsProperty` ...

Searching for `dragBounds.closestPointTo`... I do not see any other places where dragBoundsProperty has positionProperty as a dependency, and also sets positionProperty in a dragBoundsProperty listener.

**Comment by pixelzoom** [comment]
In the above commit, I set `reentrant: true` for all related instances of `dragBoundsProperty` and `positionProperty`.  It looks good in local fuzz testing, but let's see if it makes CT happy.
