### ISSUE TITLE
CT: Cannot fire when already firing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#488]
After addressing https://github.com/phetsims/geometric-optics/issues/487 for OpticalObject and its subclasses, this CT error started occurring occassionally.  I see it in geometric-optics-basics, but have not seen it in geometric-basics yet.

```
geometric-optics-basics : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737108233%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: Cannot fire when already firing
Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at assert (PushButtonModel.ts:199:14)
at (CallbackTimer.ts:129:25)
at fire (CallbackTimer.ts:105:13)
at stop (PushButtonModel.ts:137:21)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (Property.ts:65:10)
...
id: "Sparky Node Puppeteer"
Snapshot from 12/16/2023, 4:19:31 AM
```

**Comment by pixelzoom** [comment]
I don't see this in CT anymore, so I'll go ahead and close it.  It's likely that it was fixed by further work in #487.
