### ISSUE TITLE
CT: Cannot normalize a zero-magnitude vector

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#489]
After addressing https://github.com/phetsims/geometric-optics/issues/487 for OpticalObject and its subclasses, this CT error started occurring occassionally.  I see it in geometric-optics-basics, but have not seen it in geometric-basics yet.

```
geometric-optics-basics : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702689857271/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702689857271%22%2C%22timestamp%22%3A1702691389419%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Cannot normalize a zero-magnitude vector
Error: Cannot normalize a zero-magnitude vector
at (Vector2.ts:200:12)
at normalized (LightRays.ts:172:38)
at getRayDirections (LightRays.ts:94:38)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (Property.ts:65:10)
at set (AquaRadioButton.ts:185:15)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702689857271%2Fgeometric-optics-basics%2Fgeometric-optics-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702689857271%22%2C%22timestamp%22%3A1702691389419%7D
...

id: "Sparky Node Puppeteer"
Snapshot from 12/15/2023, 6:24:17 PM
```

**Comment by pixelzoom** [comment]
Duplicate of #178.
