### ISSUE TITLE
CT: value failed isValidValue: Vector2(...)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#491]
```
geometric-optics : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704195042471%22%2C%22timestamp%22%3A1704195908104%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: validation failed:
Property value not valid: value failed isValidValue: Vector2(-22, 72.5)
prunedValidator:
{
"phetioType": {
"validator": {
"validationMessage": "Validation failed IOType Validator: Vector2IO"
},
"typeName": "Vector2IO"
},
"validators": [
{
"validationMessage": "Vector2 x/y should not be NaN"
}
]
}
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/assert/js/assert.js:28:13)
at assert (validate.ts:32:16)
at validate (ReadOnlyProperty.ts:309:14)
at _notifyListeners (ReadOnlyProperty.ts:275:13)
at unguardedSet (ReadOnlyProperty.ts:259:11)
at set (Property.ts:54:10)
at (HTMLImageElementObjectNode.ts:124:57)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:123:8)
at emit (Sim.ts:413:16)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704195042471%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704195042471%22%2C%22timestamp%22%3A1704195908104%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1704195042471%2Fgeometric-optics%2Fgeometric-optics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704195042471%22%2C%22timestamp%22%3A1704195908104%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1704195042471%22%2C%22timestamp%22%3A1704195908104%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 500239
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: validation failed: Property value not valid: value failed isValidValue: Vector2(-22, 72.5) prunedValidator: {
"phetioType": {
"validator": {
"validationMessage": "Validation failed IOType Validator: Vector2IO"
},
"typeName": "Vector2IO"
},
"validators": [
{
"validationMessage": "Vector2 x/y should not be NaN"
}
]
}
[PAGE ERROR] Error: Error: Assertion failed: validation failed:
Property value not valid: value failed isValidValue: Vector2(-22, 72.5)
prunedValidator:
{
"phetioType": {
"validator": {
"validationMessage": "Validation failed IOType Validator: Vector2IO"
},
"typeName": "Vector2IO"
},
"validators": [
{
"validationMessage": "Vector2 x/y should not be NaN"
}
]
}
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/assert/js/assert.js:28:13)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/validate.js:28:17)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/ReadOnlyProperty.js:235:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/ReadOnlyProperty.js:186:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/Property.js:48:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/geometric-optics/js/common/view/HTMLImageElementObjectNode.js:96:59
at callback (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/Timer.js:29:11)
at Timer.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at http://128.138.93.172/continuous-testing/ct-snapshots/1704195042471/chipper/dist/js/joist/js/Sim.js:335:17
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 1/2/2024, 4:30:42 AM
```

**Comment by pixelzoom** [comment]
The invalid `positionProperty` value is `Vector2(-22, 72.5)`.  
`opticPositionProperty.value` is Vector2.ZERO.  
`MIN_DISTANCE_FROM_OBJECT_TO_OPTIC` is 40.
`MAX_DISTANCE_FROM_OBJECT_TO_OPTICAL_AXIS` is 100.

So the failing condition is:

```ts
Math.abs( position.x - opticPositionProperty.value.x ) >= GOConstants.MIN_DISTANCE_FROM_OBJECT_TO_OPTIC
```

**Comment by pixelzoom** [comment]
In HTMLImageElementObjectNode, the derivation of dragBoundsProperty goes through an intermediate state where the bounds are problematic.  In the above commit, I added a workaround to prevent that problematic state.  Local fuzz testing looks good. I'll leave this open for a couple of CT cycles to verify.

**Comment by pixelzoom** [comment]
CT appears to be happy. Closing.
