### ISSUE TITLE
CT: Matrix could not be inverted, determinant === 0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#492]
First noticed in geometric-optics-basics on 3/10/24, this occurs very occassionally. 

```
geometric-optics-basics : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1710062369460%22%2C%22timestamp%22%3A1710076087457%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Matrix could not be inverted, determinant === 0
Error: Matrix could not be inverted, determinant === 0
at (Matrix3.ts:808:16)
at invert (Transform3.js:231:19)
at getInverse (Node.ts:5453:48)
at renderToCanvasSubtree (Node.ts:5451:16)
at renderToCanvasSubtree (Node.ts:5451:16)
at renderToCanvasSubtree (Node.ts:5451:16)
at renderToCanvasSubtree (Node.ts:5451:16)
at renderToCanvasSubtree (Node.ts:5451:16)
at renderToCanvasSubtree (Node.ts:5451:16)
at renderToCanvasSubtree (Node.ts:5451:16)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1710062369460%2Fgeometric-optics-basics%2Fgeometric-optics-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1710062369460%22%2C%22timestamp%22%3A1710076087457%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1710062369460%2Fgeometric-optics-basics%2Fgeometric-optics-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1710062369460%22%2C%22timestamp%22%3A1710076087457%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/geometric-optics-basics/geometric-optics-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1710062369460%22%2C%22timestamp%22%3A1710076087457%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 611001
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: Error: Matrix could not be inverted, determinant === 0
at Matrix3.invert (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/dot/js/Matrix3.js:654:17)
at Transform3.getInverse (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/dot/js/Transform3.js:218:20)
at FramedImageNode.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5058:48)
at Node.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
at FramedSceneNode.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
at Node.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
at Node.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
at LensScreenView.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
at Node.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
at Node.renderToCanvasSubtree (http://128.138.93.172/continuous-testing/ct-snapshots/1710062369460/chipper/dist/js/scenery/js/nodes/Node.js:5056:17)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 3/10/2024, 3:19:29 AM
```

**Comment by pixelzoom** [comment]
Tested locally with http://localhost:8080/geometric-optics/geometric-optics_en.html?brand=phet&ea&fuzz&listenerOrder=random(611001)&audio=disabled, and could not reproduce. And I haven't seen this again after the couple of times that it occurred on 3/10/24.   So I'm going to assume this was due to something that was temporarily broken in common code, and close this issue.
