### ISSUE TITLE
CT assertion failed & y must be a finite number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#53]
```
geometric-optics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1624455729738%22%2C%22timestamp%22%3A1624457329031%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/assert/js/assert.js:25:13)
at Graph.computeWindingMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/kite/js/ops/Graph.js:1091:19)
at Graph.computeSimplifiedFaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/kite/js/ops/Graph.js:219:10)
at Function.intersectionNonZero (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/kite/js/ops/Graph.js:1341:11)
at Function.intersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/kite/js/Shape.js:2238:18)
at Spotlight.getIntersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/geometric-optics/js/lens/model/Spotlight.js:125:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/geometric-optics/js/lens/model/Spotlight.js:47:21
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/DerivedProperty.js:30:21)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 6/23/2021, 7:42:09 AM

----------------------------------

geometric-optics : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1624455729738%22%2C%22timestamp%22%3A1624457484814%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: y must be a finite number: -Infinity
Error: Assertion failed: y must be a finite number: -Infinity
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/assert/js/assert.js:25:13)
at Shape.lineTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/kite/js/Shape.js:223:15)
at LightRays.drawRays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/geometric-optics/js/common/model/LightRays.js:166:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/geometric-optics/js/common/model/LightRays.js:58:14
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/TinyEmitter.js:86:18)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/Property.js:271:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/Property.js:186:14)
at fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/sun/js/AquaRadioButton.js:116:16)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624455729738/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 6/23/2021, 7:42:09 AM
```

**Comment by veillette** [comment]
Thanks @KatieWoe ,

In one case, it is a problem with the ProjectorScreen and how the spotlight is calcutings its shape.
In the second  case, one of the lightray positions is infinity.

**Comment by veillette** [comment]
The thin lens equation (and the mirror equation) involve a sum of inverses. In the case where the focal length is equal to the distance between the object and optic, then the thin lens equation would yield infinity.

In the previous commit, we handle this situation by assigning the image distance to a very large number (but not infinite).

**Comment by veillette** [comment]
This issue seems resolved on CT. Closing
