### ISSUE TITLE
CT should be a finite Vector2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#6]
```
geometric-optics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621250602452%22%2C%22timestamp%22%3A1621253906389%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Should be a finite Vector2
Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/assert/js/assert.js:25:13)
at Image.setTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/scenery/js/nodes/Node.js:2562:17)
at Image.set translation [as translation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/scenery/js/nodes/Node.js:2579:10)
at updateScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/js/common/view/TargetImageNode.js:39:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/js/common/view/TargetImageNode.js:56:7
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 5/17/2021, 5:23:22 AM

----------------------------------

geometric-optics : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621250602452%22%2C%22timestamp%22%3A1621258752938%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Should be a finite Vector2
Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/assert/js/assert.js:25:13)
at Image.setTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/scenery/js/nodes/Node.js:2562:17)
at Image.set translation [as translation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/scenery/js/nodes/Node.js:2579:10)
at updateScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/js/common/view/TargetImageNode.js:39:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/js/common/view/TargetImageNode.js:56:7
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 5/17/2021, 5:23:22 AM

----------------------------------

geometric-optics : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1621250602452%22%2C%22timestamp%22%3A1621255665365%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Should be a finite Vector2
Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/assert/js/assert.js:25:13)
at Image.setTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/scenery/js/nodes/Node.js:2562:17)
at Image.set translation [as translation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/scenery/js/nodes/Node.js:2579:10)
at updateScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/js/common/view/TargetImageNode.js:39:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/geometric-optics/js/common/view/TargetImageNode.js:56:7
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621250602452/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 5/17/2021, 5:23:22 AM
```

**Comment by KatieWoe** [comment]
May be related:
```
geometric-optics : build
Build failed with status code 1:
Running "report-media" task
>> not-annotated: geometric-optics/images/pencil-3d-inverted.png
>> not-annotated: geometric-optics/images/pencil-3d-reversed-inverted.png
Fatal error: There is an issue with the licenses for media types.
Snapshot from 5/19/2021, 7:23:16 PM

----------------------------------

geometric-optics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621473796274%22%2C%22timestamp%22%3A1621489929983%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Line end should be a Vector2: null
Error: Assertion failed: Line end should be a Vector2: null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/assert/js/assert.js:25:13)
at Line.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/kite/js/segments/Line.js:195:15)
at new Line (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/kite/js/segments/Line.js:33:10)
at LineStyles.leftJoin (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/kite/js/util/LineStyles.js:172:15)
at Subpath.stroked (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/kite/js/util/Subpath.js:523:40)
at Shape.getStrokedBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/kite/js/Shape.js:1557:45)
at Path.computeShapeBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Path.js:339:34)
at Path.updateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Path.js:264:47)
at Path.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Node.js:1184:40)
at Path.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Node.js:1212:31)
id: Bayes Chrome
Snapshot from 5/19/2021, 7:23:16 PM

----------------------------------

geometric-optics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621473796274%22%2C%22timestamp%22%3A1621502719039%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Should be a finite Vector2
Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/assert/js/assert.js:25:13)
at Image.setTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Node.js:2562:17)
at Image.set translation [as translation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Node.js:2579:10)
at updateScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/js/common/view/TargetImageNode.js:45:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/js/common/view/TargetImageNode.js:60:7
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 5/19/2021, 7:23:16 PM

----------------------------------

geometric-optics : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1621473796274%22%2C%22timestamp%22%3A1621490068219%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Should be a finite Vector2
Error: Assertion failed: Should be a finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/assert/js/assert.js:25:13)
at Image.setTranslation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Node.js:2562:17)
at Image.set translation [as translation] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/scenery/js/nodes/Node.js:2579:10)
at updateScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/js/common/view/TargetImageNode.js:45:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/geometric-optics/js/common/view/TargetImageNode.js:60:7
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621473796274/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 5/19/2021, 7:23:16 PM
```

**Comment by veillette** [comment]
The problem with the license is addressed with https://github.com/phetsims/geometric-optics/commit/9067e7cb3438e581024099cd8b359a60ece831b1

**Comment by veillette** [comment]
Bayes seems to hit the "Should be a finite Vector2" on a pretty regular bases but I cant reproduce it .

**Comment by veillette** [comment]
Superseded by #53
