### ISSUE TITLE
CT: Assertion failed: Line end should be a Vector2: null

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#60]
```
geometric-optics : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/geometric-optics/geometric-optics_en.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1624596727568%22%2C%22timestamp%22%3A1624603949845%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Line end should be a Vector2: null
Error: Assertion failed: Line end should be a Vector2: null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/assert/js/assert.js:25:13)
at Line.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/kite/js/segments/Line.js:195:15)
at new Line (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/kite/js/segments/Line.js:33:10)
at LineStyles.leftJoin (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/kite/js/util/LineStyles.js:172:15)
at LineStyles.rightJoin (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/kite/js/util/LineStyles.js:205:17)
at Subpath.stroked (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/kite/js/util/Subpath.js:531:41)
at Shape.getStrokedBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/kite/js/Shape.js:1557:45)
at Path.computeShapeBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/scenery/js/nodes/Path.js:339:34)
at Path.updateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/scenery/js/nodes/Path.js:264:47)
at Path.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1624596727568/scenery/js/nodes/Node.js:1184:40)
id: Bayes Chrome
Snapshot from 6/25/2021, 12:52:07 AM
```

**Comment by veillette** [comment]
We are passing CT on a regular basis. Closing
